---
- name: restart target network services
  ansible.builtin.command:
    cmd: docker compose -f {{ target_network_compose_file }} restart
  changed_when: true

- name: restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
