---
- name: restart gitea
  ansible.builtin.command:
    cmd: docker compose -f {{ report_repository_compose_file }} restart
  changed_when: true

- name: restart docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
